import { Point, WallSegment, Room } from '@/types/floorPlanTypes';

/**
 * Detect enclosed areas from wall segments and create automatic floor polygons
 */
export function detectFloorsFromWalls(wallSegments: WallSegment[]): Room[] {
  if (wallSegments.length === 0) return [];

  // Build a graph of wall connections
  const graph = buildWallGraph(wallSegments);
  
  // Find closed loops in the graph
  const loops = findClosedLoops(graph);
  
  // Convert loops to room polygons
  const detectedRooms: Room[] = loops.map((loop, index) => ({
    id: `auto-floor-${index}`,
    name: `Auto Floor ${index + 1}`,
    points: loop,
    area: calculatePolygonArea(loop),
    perimeter: calculatePolygonPerimeter(loop),
    isAutoGenerated: true
  }));

  return detectedRooms;
}

/**
 * Build a graph representation of wall connections
 */
function buildWallGraph(wallSegments: WallSegment[]): Map<string, Point[]> {
  const graph = new Map<string, Point[]>();
  const tolerance = 20; // 20px tolerance for connection

  wallSegments.forEach(wall => {
    const startKey = pointToKey(wall.start, tolerance);
    const endKey = pointToKey(wall.end, tolerance);

    if (!graph.has(startKey)) graph.set(startKey, []);
    if (!graph.has(endKey)) graph.set(endKey, []);

    graph.get(startKey)!.push(wall.end);
    graph.get(endKey)!.push(wall.start);
  });

  return graph;
}

/**
 * Find closed loops in the wall graph using DFS
 */
function findClosedLoops(graph: Map<string, Point[]>): Point[][] {
  const loops: Point[][] = [];
  const visited = new Set<string>();

  for (const [startKey, connections] of graph) {
    if (visited.has(startKey) || connections.length < 2) continue;

    const startPoint = keyToPoint(startKey);
    const path = [startPoint];
    const pathKeys = new Set([startKey]);

    if (findLoop(graph, startPoint, path, pathKeys, visited)) {
      if (path.length >= 4) { // At least 4 points for a valid room
        loops.push([...path]);
        path.forEach(point => visited.add(pointToKey(point, 20)));
      }
    }
  }

  return loops;
}

/**
 * Recursive function to find a closed loop from current point
 */
function findLoop(
  graph: Map<string, Point[]>,
  currentPoint: Point,
  path: Point[],
  pathKeys: Set<string>,
  globalVisited: Set<string>
): boolean {
  const currentKey = pointToKey(currentPoint, 20);
  const connections = graph.get(currentKey) || [];

  for (const nextPoint of connections) {
    const nextKey = pointToKey(nextPoint, 20);

    // Check if we've found a loop back to start
    if (path.length > 3 && nextKey === pointToKey(path[0], 20)) {
      return true;
    }

    // Continue exploring if we haven't visited this point in current path
    if (!pathKeys.has(nextKey) && !globalVisited.has(nextKey)) {
      path.push(nextPoint);
      pathKeys.add(nextKey);

      if (findLoop(graph, nextPoint, path, pathKeys, globalVisited)) {
        return true;
      }

      // Backtrack
      path.pop();
      pathKeys.delete(nextKey);
    }
  }

  return false;
}

/**
 * Convert point to string key with tolerance for snapping
 */
function pointToKey(point: Point, tolerance: number): string {
  const x = Math.round(point.x / tolerance) * tolerance;
  const y = Math.round(point.y / tolerance) * tolerance;
  return `${x},${y}`;
}

/**
 * Convert string key back to point
 */
function keyToPoint(key: string): Point {
  const [x, y] = key.split(',').map(Number);
  return { x, y };
}

/**
 * Calculate polygon area using shoelace formula
 */
function calculatePolygonArea(points: Point[]): number {
  if (points.length < 3) return 0;

  let area = 0;
  for (let i = 0; i < points.length; i++) {
    const j = (i + 1) % points.length;
    area += points[i].x * points[j].y;
    area -= points[j].x * points[i].y;
  }
  return Math.abs(area) / 2;
}

/**
 * Calculate polygon perimeter
 */
function calculatePolygonPerimeter(points: Point[]): number {
  if (points.length < 2) return 0;

  let perimeter = 0;
  for (let i = 0; i < points.length; i++) {
    const j = (i + 1) % points.length;
    const dx = points[j].x - points[i].x;
    const dy = points[j].y - points[i].y;
    perimeter += Math.sqrt(dx * dx + dy * dy);
  }
  return perimeter;
}