// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfdbqfbodppniqzoxnyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZGJxZmJvZHBwbmlxem94bnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzMyNzYsImV4cCI6MjA2NjMwOTI3Nn0.L0MBXYWb5cLjTbVvfY6__RFGucf43otrowhwOe2zB9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);